--- # 监控中心配置
spring.boot.admin.client:
  # 增加客户端开关
  enabled: false
  url: http://localhost:9090/admin
  instance:
    service-host-type: IP
  username: interview
  password: 123456

--- # xxl-job 配置
xxl.job:
  # 执行器开关
  enabled: false
  # 调度中心地址：如调度中心集群部署存在多个地址则用逗号分隔。
  admin-addresses: http://localhost:9100/xxl-job-admin
  # 执行器通讯TOKEN：非空时启用
  access-token: xxl-job
  executor:
    # 执行器AppName：执行器心跳注册分组依据；为空则关闭自动注册
    appname: xxl-job-executor
    # 28080 端口 随着主应用端口飘逸 避免集群冲突
    port: 2${server.port}
    # 执行器注册：默认IP:PORT
    address:
    # 执行器IP：默认自动获取IP
    ip:
    # 执行器运行日志文件存储磁盘路径
    logpath: ./logs/xxl-job
    # 执行器日志文件保存天数：大于3生效
    logretentiondays: 30

--- # 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      # 性能分析插件(有性能损耗 不建议生产环境使用)
      p6spy: true
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      # 严格模式 匹配不到数据源则报错
      strict: true
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
          # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能(对数据库有性能损耗 使用批量操作应考虑性能问题)
          url: jdbc:mysql://10.104.70.245:3306/ai_interview?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
          username: root
          password: Hky123456.
#        hky:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://10.104.70.245:3306/zs_datacenter?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
#          username: root
#          password: Hky123456.

#        hky:
#           driver-class-name: com.mysql.cj.jdbc.Driver
#           url: jdbc:mysql://210.43.32.29:33066/zs_datacenter?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
#           username: GXFNAI
#           password: MySQL!@#gxfnai2024
        # 从库数据源
#        slave:
#          lazy: true
#          type: ${spring.datasource.type}
#          driverClassName: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
#          username:
#          password:
#        oracle:
#          type: ${spring.datasource.type}
#          driverClassName: oracle.jdbc.OracleDriver
#          url: jdbc:oracle:thin:@//localhost:1521/XE
#          username: ROOT
#          password: root
#        postgres:
#          type: ${spring.datasource.type}
#          driverClassName: org.postgresql.Driver
#          url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&reWriteBatchedInserts=true
#          username: root
#          password: root
#        sqlserver:
#          type: ${spring.datasource.type}
#          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#          url: jdbc:sqlserver://localhost:1433;DatabaseName=tempdb;SelectMethod=cursor;encrypt=false;rewriteBatchedStatements=true
#          username: SA
#          password: root
      hikari:
        # 最大连接池数量
        maxPoolSize: 20
        # 最小空闲线程数量
        minIdle: 10
        # 配置获取连接等待超时的时间
        connectionTimeout: 30000
        # 校验超时时间
        validationTimeout: 5000
        # 空闲连接存活最大时间，默认10分钟
        idleTimeout: 600000
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        maxLifetime: 1800000
        # 多久检查一次连接的活性
        keepaliveTime: 30000

--- # redis 单机配置(单机与集群只能开启一个另一个需要注释掉)
spring:
  redis:
    # 地址
    host: 10.104.70.245
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 4
    # 密码(如没有密码请注释掉)
    password: Hky123456.
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl: false

redisson:
  # redis key前缀
  keyPrefix:
  # 线程池数量
  threads: 4
  # Netty线程池数量
  nettyThreads: 8
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: ${interview.name}
    # 最小空闲连接数
    connectionMinimumIdleSize: 8
    # 连接池大小
    connectionPoolSize: 32
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50

--- # mail 邮件发送
mail:
  enabled: false
  host: smtp.163.com
  port: 465
  # 是否需要用户名密码验证
  auth: true
  # 发送方，遵循RFC-822标准
  from: xxx@163.com
  # 用户名（注意：如果使用foxmail邮箱，此处user为qq号）
  user: xxx@163.com
  # 密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）
  pass: xxxxxxxxxx
  # 使用 STARTTLS安全连接，STARTTLS是对纯文本通信协议的扩展。
  starttlsEnable: true
  # 使用SSL安全连接
  sslEnable: true
  # SMTP超时时长，单位毫秒，缺省值不超时
  timeout: 0
  # Socket连接超时值，单位毫秒，缺省值不超时
  connectionTimeout: 0

--- # sms 短信 支持 阿里云 腾讯云 云片 等等各式各样的短信服务商
# https://wind.kim/doc/start 文档地址 各个厂商可同时使用
sms:
  # 阿里云 dysmsapi.aliyuncs.com
  alibaba:
    #请求地址 默认为 dysmsapi.aliyuncs.com 如无特殊改变可以不用设置
    requestUrl: dysmsapi.aliyuncs.com
    #阿里云的accessKey
    accessKeyId: xxxxxxx
    #阿里云的accessKeySecret
    accessKeySecret: xxxxxxx
    #短信签名
    signature: 测试
  tencent:
    #请求地址默认为 sms.tencentcloudapi.com 如无特殊改变可不用设置
    requestUrl: sms.tencentcloudapi.com
    #腾讯云的accessKey
    accessKeyId: xxxxxxx
    #腾讯云的accessKeySecret
    accessKeySecret: xxxxxxx
    #短信签名
    signature: 测试
    #短信sdkAppId
    sdkAppId: appid
    #地域信息默认为 ap-guangzhou 如无特殊改变可不用设置
    territory: ap-guangzhou

casdoor:
  endpoint: https://cas.ruanzhuinfo.com
  client-id: 561826f0717c4ee9b88d
  client-secret: aa4329f0e2eeb59ebe4a3058860445ea3a2a9885
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIE3TCCAsWgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCgxDjAMBgNVBAoTBWFk
    bWluMRYwFAYDVQQDEw1jZXJ0LWJ1aWx0LWluMB4XDTI1MDEwNjA0MjkwNVoXDTQ1
    MDEwNjA0MjkwNVowKDEOMAwGA1UEChMFYWRtaW4xFjAUBgNVBAMTDWNlcnQtYnVp
    bHQtaW4wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDI2JKKcA9URONk
    l4OC351dDDgebSCL4DPQtkB4HjLgqQz6AtfaNxUPsfOdlLImgwFsot53t3YqgOjG
    LBn0XwLHWA/J7iVArox9jvPv1SNN6kVvrXYruv9czh7g4/BorukeQEbdQP6bawde
    6Eb0azF4agai56uEzLyjksGB5qUtVOz3i1+Ekt86pf4vAMlgln6uQcdVKcnj/ff2
    x4HqROOZPMH1geBBupo+mqRjFMP/mQPZKa5mI7oTiN8fXlYM+ANZhTIpphFeKdRn
    yu9h1vInQooDFLJ+dFJCMdy+TVD8nkydg1vcwB02u2kubd8Qo8hqQ2rEVAk2MT2W
    zw5ME7AvmNXAJerQoK9LzMnHUShL7ckhGihJzMV/Az7iIK9vRCS1hv52vEUt1LDW
    3O5/z4yga0YXYMZAKtK2AQZX5A05nZOpIBOiCtNL5t4JkeHjUWMyWH4kF5MzQUH2
    OBTlV5gFvz1HYVPmuRDaoGUkfsk0kX4VI4o2Bcyqr+eHnyL9mY6qlwxgCldgCalR
    DQQa9aixlZ0NPO4rlcWMtkg0HzoctKYqueeNCohJx5kDBp5BWajWlZIJkAecc0eM
    Nl7zxCJ7q1kosr6TpEeDDmWZtS19uDzlHMqIqpoizlScQZ1w9dQMLvcS7+Uy7jtN
    N6xHnHU8VG0pY3KwDg5bOBM09OceXwIDAQABoxAwDjAMBgNVHRMBAf8EAjAAMA0G
    CSqGSIb3DQEBCwUAA4ICAQCvXYSdmAXA/BmxZPWhtQKfQfGT+OVEBbM6iiwKUfiH
    aIFYQYVSH/MEA1fLxj54XLt5chp/NMll4mrlx7C/sRIq+Lua9MObw0zapZam9n8I
    G2+2aotyySeJa109xteFYXvi600w4m2LWRiX5hHBwRVIvF5Vg1HERwAQB7fTSQcY
    BAkylpM84pg/SX0nGwnuuNV3J27HeyVfPMQAOuv2bQQgnrnaW6xmuKEhFtbCRXuK
    Ggs61V5eBqcEVVl5Byvhl0Z7SHaQqxcDhSKtDeujsGUb2S43GShV/GX+3lYVKUwA
    CruKb9w+OrXFdAeaeQVJPKYpF5Ny/Y68kq9IAReM68beDzc6unrYkOiDTMXSwR3S
    x26ZSMdoQSjLyN27WPmFtBfRc9VKHAmuWM0KmjvEgn2jXj7gz4N1tHrVZzsk5SZV
    Rh3JEZf2MLy4ChaGLFnFMxxelTuygOJKzgyF7AoVL2Ull+8/GnvuCc5XXURatl7n
    rDYN31XN8m2SY06zOH1pVPs21dm3W0yj5AKuR6VJv6sIdiyPnoTjioWikEjBDKjk
    u9kXyIC0xLfhjNBmEvtPLlYVzr13Xz2Hao3KgvnTeSVPOlfut1Ac+0met913C06z
    4K7BZnLG9R5zeoL1ZUlwI9kdgdRPdd+6ICz/bH+KvAXHVdQgcbedhqp86yJv6A51
    4Q==
    -----END CERTIFICATE-----
  organization-name: built-in
#  application-name: app-built-in

cas:
  #  上一次访问的什么地址，service后面就跟什么
  # 代理的话，service后面就跟代理后的地址
  server-login-url: https://auth.hist.edu.cn/cas/login
  client-host-url: http://10.104.70.245:8080/interview_v1
  validation-type: cas
  # 不加配置，默认拦截所有的请求
  authentication-url-patterns: /hkyLogin
  server-url-prefix: https://auth.hist.edu.cn/cas
